### ISSUE TITLE
Discord+ doesn't look as shown in the images, is there any fix?

### ISSUE THREAD

**Issue by A-Random-Lantern** [PlusInsta/discord-plus#23] opened 2019-09-11 00:59 UTC
![image](https://user-images.githubusercontent.com/23159237/64660338-da154080-d40d-11e9-9518-cfc4e169d36d.png)

**Comment by PlusInsta** [comment] 2019-09-11 06:46
Duplicate of #21. A fix is in the works. Check out the beta branch in the meantime.

**Closed by PlusInsta** 2019-09-11 06:46 UTC
