### ISSUE TITLE
Not Transparent

### ISSUE THREAD

**Issue by Ramrodio** [PlusInsta/discord-plus#22] opened 2019-09-10 17:20 UTC
Nothing is transparent and I can't see my background.. Maybe I did something wrong or maybe it was an update. I dunno.

**Comment by PlusInsta** [comment] 2019-09-10 19:03
End-users are supposed to use `DiscordPlus-master.theme.css`, not the source code file. Additionally, the issue itself is a duplicate of #21. Closing this as invalid.

**Closed** 2019-09-10 19:03 UTC
Labels: duplicate, invalid
